**Introduction to NumPy**

1. **What is NumPy?**

NumPy (Numerical Python) is a powerful and widely used Python library that provides essential tools for numerical computing. It offers efficient multidimensional arrays, linear algebra operations, mathematical functions, and random number generation, making it a cornerstone for data analysis, machine learning, and scientific computing in Python.

Key Points about NumPy:

1. **Efficiency**: NumPy arrays are optimized for speed, making them significantly faster than standard Python lists for numerical computations.
2. **Multidimensionality:** NumPy supports creating and working with arrays of various dimensions (1D, 2D, 3D, etc.), providing flexibility for representing complex data structures.
3. **Linear Algebra:** NumPy offers a rich set of functions for linear algebra operations like matrix multiplication, inversion, and eigenvalue decomposition, crucial for many machine learning algorithms.
4. **Integration with Other Libraries:** NumPy seamlessly integrates with other scientific Python libraries like pandas (data analysis) and SciPy (optimization, integration, etc.), forming a powerful ecosystem for data science and scientific computing.

2. install numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


2. **Verification**

Once you've installed NumPy using either method, open a Python interpreter (type python or python3 in your terminal) and try the following code:

In [2]:
import numpy as np

In [4]:
ls=np.array([1,2,3,4,5])
ls
print(type(ls))

<class 'numpy.ndarray'>


From Lists

In [5]:
import numpy as np

data = [1, 2, 3, 4, 5]
arr_from_list = np.array(data)

print(arr_from_list)  


[1 2 3 4 5]


Using Functions

np.zero

In [7]:
zeros_arr = np.zeros((3, 3)) 
print(zeros_arr)  


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


np.ones

In [9]:
ones_arr = np.ones((3, 4)) 
print(ones_arr)  


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
ones_arr[1,2]

1.0

Array Indexing and Slicing:

In [14]:
arr = np.array([10, 20, 30, 40])
first_element = arr[1] 
print(first_element) 


20


Multi-Dimensional Indexing

In [16]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
second_row_first_element = arr_2d[1, 2]  
print(second_row_first_element) 

6
