Day 3: Linear Algebra for Machine Learning with NumPy

This session dives into the fundamental concepts of linear algebra essential for machine learning algorithms, all implemented using NumPy:

1. Vectors and Matrices:

**Vectors (1D Arrays)**: Represent single data points with a list of numerical values. In NumPy, these are simply 1-dimensional arrays.

In [1]:
import numpy as np

data_point = np.array([5, 2, 1.7])

# Print the vector
print(data_point)  


[5.  2.  1.7]


**Matrices (2D Arrays):** Represent collections of data points arranged in rows and columns. These are 2-dimensional NumPy arrays.

In [12]:

# Sample data points as rows
data_points = np.array([[3, 1], [4, 2], [5, 1.5]])

# Print the matrix
print(data_points) 


[[3.  1. ]
 [4.  2. ]
 [5.  1.5]]


2. Dot Product:

The dot product (vector multiplication) calculates a scalar value representing the magnitude of the linear relationship between two vectors. It's crucial in machine learning tasks like linear regression and finding similarities between data points.

In [13]:
# Sample vectors
vector1 = np.array([1, 2])
vector2 = np.array([3, 4])

# Dot product using np.dot()
dot_product = np.dot(vector1, vector2)
print(dot_product)  

11


3. Matrix Operations:

NumPy provides functions for various matrix operations:

**Matrix Addition (Element-wise)**: Adds corresponding elements of two matrices with the same dimensions.

In [17]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

added_matrix = matrix1 + matrix2
print(added_matrix) 
print(matrix1) 
print(matrix2) 



[[ 6  8]
 [10 12]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


**Matrix Subtraction (Element-wise):** Subtracts corresponding elements of two matrices with the same dimensions.

In [6]:
subtracted_matrix = matrix1 - matrix2
print(subtracted_matrix)

[[-4 -4]
 [-4 -4]]


In [18]:
np.maximum(matrix1, matrix2)

array([[5, 6],
       [7, 8]])

In [19]:
np.max(matrix2)

8

In [20]:
np.minimum(matrix1,matrix2)

array([[1, 2],
       [3, 4]])

In [21]:
np.min(matrix1)

1